// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI_Project.API.DB;

#nullable disable

namespace WebAPI_Project.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230915170047_First Migration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI_Project.API.Models.Domain.BlogItem", b =>
                {
                    b.Property<Guid>("blog_item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("blog_item_author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("blog_item_description_long")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("blog_item_description_short")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("blog_item_image_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("blog_item_isvisible")
                        .HasColumnType("bit");

                    b.Property<DateTime>("blog_item_publish_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("blog_item_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("blog_item_url_handle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("blog_item_id");

                    b.ToTable("BlogItems");
                });

            modelBuilder.Entity("WebAPI_Project.API.Models.Domain.Category", b =>
                {
                    b.Property<Guid>("category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("category_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("category_url_handle")
                        .HasColumnType("bit");

                    b.HasKey("category_id");

                    b.ToTable("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
